repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: local
    hooks:
      - id: sort_imports
        name: sort imports
        entry: ruff check --select=I,F401 --fix
        language: system
        types_or:
          - cython
          - pyi
          - python
        require_serial: true
      - id: ruff_format
        name: ruff format
        entry: ruff format
        language: system
        types:
          - python
        require_serial: true
      - id: ruff_check
        name: ruff check
        entry: ruff check
        language: system
        types:
          - python
        require_serial: true
      - id: mypy
        name: mypy
        entry: poetry run mypy
        files: src
        language: system
        types:
          - python
        require_serial: true
